[#148] Autocomple for 'Raw Fact' strings
projecthamster/hamster-gtk pull request #150
Opened 2016-11-15 12:25 UTC by elbenfreund

This PR changes the way raw fact strings are handled by our GUI.
Instead of using a generic ``Gtk.Entry`` we introduce a new ``RawFactEntry`` class to handle the specific requirements of 'raw fact' strings. 
Autocompletion is provided by a customized ``EntryCompletion`` class called ``RawFactCompletion``.
Both custom classes are to be used in conjunction.

The basic approach to the problem at hand is as follows.

1. ``RawFactEntry._on_changed`` decomposes the current raw fact string and tries to map its substrings to activity, category, tags, etc... segments. This is done with the help of regex matching.
2. If the entry text could be mapped at all, the entry uses the current cursor position to make a guess what segment the user is currently trying to specify.
3. If the currently edited segment is one that we want to provided autocompletion for, the appropiate model is set on the completion instance and the completion machinery is launched.
4. If the user selects a completion suggestion, the original segment text gets replaced by the completion text and the cursor placed at the segment end.

There are quite some subtleties involved as the result of our non standard matching/autocomplete requirements applying only to substrings of the entry (for more details see the commit msg and code annotations) but this is the gist of it.

One central cornerstone of this solution is our new 'raw fact' regex. This entire approach depends on our ability to come up with a regex that is able to capture the semantics of our raw fact string sufficiently well.
Please not that this does not include any validation at all.
*If* this works out, we may even have a good candidate to refactor ``hamster_lib.Fact.create_from_raw_fact`` to use this regex based solution instead of its current rather hacky one.

2016-11-15 18:55 UTC, jtojnar commented
At a glance, it looks reasonable. I am mostly concerned about the `decompose_raw_fact_string` helper.

1. Descriptions cannot contain at-signs or hashes – `foo@bar, @baz` or `foo@bar, #baz` do not match anything.
2. Tags can contain at-signs, though – `foo #@bar` does match.
3. Relative times are not matched.
4. Category without activity can be matched.
5. The function returns the matches including separators and spaces.

2016-11-16 12:47 UTC, elbenfreund commented
You are totally right to be concerned about ``decompose_raw_fact_string``. This clearly carries a lot of weight and is hard to get right.
What I did here is just a first and relatively restrictive approximation. By composing the regex in such a modular way we should be able to experiment quite easily to hopefully find something that works nicely.
The challenge is to create a regex that matches valid strings, but also is powerfull and flexible enough to have a good change of matching incomplete strings sufficiently well.
The legacy parsing has its own issues and by now I would be willing to break compatibility if that would be really needed for a clear, concise and transparent raw fact string semantic (for example, one could consider using ``;`` as a description seperator instead.

Now on to you first feedback.
1. Yes, and I agree that it would be good to allow as many characters in the description (including ``@`` and ``#`` as possible. I will add a commit that will give this a try. There is always the risk of side effects but this is something only experience will show.
2. That is deliberate: as I said, I try to limit the char-set as little as possible wherever possible.
3. Yes, thats something still to be done. Thanks for the reminder.
4. That is intensional. As this is not a ``create from raw fact`` but rather a 'get me all the information contained in the string'  function this is exactly the way we want it to behave.
5. Yes. I wanted to make sure that the function makes as little preassumptions about the way it is used as possible. Right now ``RawFactEntry`` provides its own prefix removal and alllows easy access to the cleaned up segment text via ``RawFactEntry.get_segment_text``. If this a recurring issue, prefix removal could be outsourced to a seperate helper method that provides cleaned up strings.

2017-01-31 09:02 UTC, jtojnar requested changes

2017-01-31 09:02 UTC, jtojnar commented on hamster_gtk/helpers.py
> +        raw (bool): If True, return the raw match instance, if ``False`` return
`False` is backticked here, while `True` is not.

2017-01-31 09:02 UTC, jtojnar commented on README.rst
>    libgtk-3-dev``.
Forgotten closing backticks.

2017-01-31 09:02 UTC, jtojnar commented on hamster_gtk/helpers.py
> +        This not withstanding can however be the bases for future implementations
Notwithstanding is a single word, however is probably redundant, and bases should be basis.

2017-01-31 09:02 UTC, jtojnar commented on hamster_gtk/misc/widgets/raw_fact_entry.py
> +    """A custom entry widgets that provides ``faw fact`` specific autocompletion behaviour."""
widgets → widget, faw → raw

2017-01-31 09:02 UTC, jtojnar commented on hamster_gtk/helpers.py
> +    activity_regex = r'[^@:]+'
I am still not fully convinced this is the way to go. [Partial matches](https://pypi.python.org/pypi/regex) could be also considered.

2017-01-31 09:02 UTC, jtojnar commented on hamster_gtk/misc/widgets/raw_fact_entry.py
> +        if add_prefix:
This will always be `True` as the argument is shadowed by the helper function.

2017-01-31 09:02 UTC, jtojnar commented on hamster_gtk/misc/widgets/raw_fact_entry.py
> +    def replace_segment_string(self, segment_string, add_prefix=True):
What is the purpose of the `add_prefix` when it is never used?

2017-01-31 09:02 UTC, jtojnar commented on hamster_gtk/misc/widgets/raw_fact_entry.py
> +    def get_segment_text(self, remove_prefix=True):
What is the purpose of the `remove_prefix` when it is never used?

2017-01-31 09:02 UTC, jtojnar commented on hamster_gtk/misc/widgets/raw_fact_entry.py
> +        if remove_prefix:
The argument is shadowed by the function.

2017-01-31 09:02 UTC, jtojnar commented on hamster_gtk/misc/widgets/raw_fact_entry.py
> +            result = string
In `add_prefix` this is in the else block, it should be unified.

2017-01-31 09:02 UTC, jtojnar commented on hamster_gtk/misc/widgets/raw_fact_entry.py
> +    def _on_facts_changed(self, evtl):
evtl?

2017-01-31 09:02 UTC, jtojnar commented on hamster_gtk/misc/widgets/raw_fact_entry.py
> +        user is currently editing. For this the whole string is inspecred and matched
inspecred

2017-01-31 09:02 UTC, jtojnar commented on hamster_gtk/misc/widgets/raw_fact_entry.py
> +        against our regex. By coparing the current cursor position with individual
coparing

2017-01-31 09:02 UTC, jtojnar commented on hamster_gtk/misc/widgets/raw_fact_entry.py
> +    def replace_segment_string(self, segment_string, add_prefix=True):
Also, should not this method by private?

2017-01-31 09:02 UTC, jtojnar commented on hamster_gtk/misc/widgets/raw_fact_entry.py
> +    def get_segment_text(self, remove_prefix=True):
Also, should not this method by private?

2017-01-31 09:02 UTC, jtojnar commented on hamster_gtk/misc/widgets/raw_fact_entry.py
> +        """instantiate class."""
Should begin with capital letter.

2017-01-31 09:02 UTC, jtojnar commented on hamster_gtk/misc/widgets/raw_fact_entry.py
> +        activities, categories = [], []
Why not just use set again?

2017-01-31 09:02 UTC, jtojnar commented on hamster_gtk/misc/widgets/raw_fact_entry.py
> +        This is the place were we define which reference frame should be used
were → where

2017-01-31 09:02 UTC, jtojnar commented on hamster_gtk/helpers.py
> +    activity_regex = r'[^@:]+'
Additionally, I think `a#b@c` should be parsed as `{'activity': 'a', 'tags': '#b@c'}`, that is `#` should be banned from `activity`.

2017-01-31 09:06 UTC, jtojnar commented
Additionally, the separate autocomplete for activities and categories makes no sense to me. After all, each activity has a fixed category. I like how the code is structured, though; it will come in handy for tag autocompletion.

2017-02-01 19:10 UTC, elbenfreund commented on hamster_gtk/helpers.py
> +    activity_regex = r'[^@:]+'
Is there a particular argument to be had for "banning ``#`` within the activity name"?
I personally do not care either way, but I think a general rule "allow as much as possible, unless for technical reasons" makes sense?

2017-02-01 19:24 UTC, jtojnar commented on hamster_gtk/helpers.py
> +    activity_regex = r'[^@:]+'
Otherwise, `a #b` would be ambiguous, I think.

2017-02-02 08:59 UTC, elbenfreund commented
With regards to splitting autocomplete for activity and category:

Please not that it *is true* that each ``Actitivity`` has at max. one category assigned, but ``Activity.name`` ``is not`` a unique (natural) key! Only ``Activity.name + Activity.category`` as a composite key are unique.

Now, this may be something one could do different, but for now this is how ``hamster-lib`` (following legacy hamster for compatibility) handles things.

Now, that does not by itself mean that autocompletion could not behave differently to its current suggestion. For starters, when looking up categories, it may very well make sense to just look up categories that "match" the already known activity (instead of all fetched ones). Or one threats the "activity string" as the whole of "name + category" and looks it up as a whole.
At this point the given solution seemed to strike a balance between flexibility and implementation effort.
I think it would be good not to focus too much on user preferences but get the general machinery in place. Details like this can then be easily adapted to RL user expectations.

2017-02-02 09:01 UTC, elbenfreund commented on hamster_gtk/misc/widgets/raw_fact_entry.py
> +        activities, categories = [], []
The original reason was to keep the "order information" so one could use it to prioritize matches. But if we ever implement a more clever matching solution (may in line with legacy hamster) we can just remove the ``set``. So you are right, as it is now its neither here nor there...

2017-02-02 09:25 UTC, elbenfreund commented on hamster_gtk/misc/widgets/raw_fact_entry.py
> +    def replace_segment_string(self, segment_string, add_prefix=True):
I think it is a rather generic method and thought to make it part of the public API. Which is also why I included the ``add_prefix`` in the signature - to increase user ease. But you are right, I can not really come up with a usecase where one would want to deal with prefixing itself (e.g. one would use ``add_prefix=False``). Going to remove it.

2017-02-02 09:34 UTC, elbenfreund commented on hamster_gtk/misc/widgets/raw_fact_entry.py
> +    def get_segment_text(self, remove_prefix=True):
Same as ``replace_segment_string``

2017-02-02 09:34 UTC, jtojnar commented
Matching against `{name}@{category}` seems to be what hamster 2 is doing. It also feels more natural.

2017-02-02 09:36 UTC, elbenfreund commented on hamster_gtk/misc/widgets/raw_fact_entry.py
> +            result = string
Yes. I can never make up my mind which to find better.

2017-02-02 09:42 UTC, elbenfreund commented on hamster_gtk/helpers.py
> +    activity_regex = r'[^@:]+'
that should be ``Activity.name='a', Activity.tags={b}``, or not?

2017-02-02 09:48 UTC, jtojnar commented on hamster_gtk/helpers.py
> +    activity_regex = r'[^@:]+'
I think this regex parses it as `Activity(name='a #b')`.

2017-02-11 19:23 UTC, jtojnar requested changes

2017-02-11 19:23 UTC, jtojnar commented on hamster_gtk/misc/widgets/raw_fact_entry.py
> +        start = match.start('activity')
This should probably allow matching start of category when activity is not specified. At least this is how it behaves in hamster-master.

2017-02-11 19:23 UTC, jtojnar commented on hamster_gtk/misc/widgets/raw_fact_entry.py
> +        tuple: Tuple (int, int) representing the given segments start and end position.
segment's

2017-02-11 19:23 UTC, jtojnar commented on hamster_gtk/misc/widgets/raw_fact_entry.py
> +        Instantiate class.
Should be initialize.

2017-02-11 19:23 UTC, jtojnar commented on hamster_gtk/misc/widgets/raw_fact_entry.py
> +            result = self.match.group('activity')
To allow matching just on categories, something like `result = (self.match.group('activity') or '') + (self.match.group('category') or '')` should be used.

2017-02-15 10:35 UTC, jtojnar commented on hamster_gtk/misc/widgets/raw_fact_entry.py
> +        if start == -1:
This should probably be the same as the second condition.

2017-02-15 10:35 UTC, jtojnar commented on hamster_gtk/misc/widgets/raw_fact_entry.py
> +            result
Forgotten line

2017-02-15 16:12 UTC, elbenfreund commented
Ready for you :)

2017-02-15 17:12 UTC, jtojnar approved these changes

2017-02-15 19:45 UTC, merged