At information about migrating from legacy hamster
projecthamster/hamster-gtk pull request #157
Opened 2017-01-30 23:35 UTC by elbenfreund

Closes: #130

2017-01-30 23:43 UTC, jtojnar requested changes

2017-01-30 23:43 UTC, jtojnar commented on README.rst
> +This new version of hamster significantly raises the standart in terms of data consistency. Unlike
standard

2017-01-30 23:43 UTC, jtojnar commented on README.rst
> +There will be a way to import data that still constitutes valid 'facts' (that
constitute

2017-01-30 23:43 UTC, jtojnar commented on README.rst
> +resolve migration conflicts (unless someone new pitches is of cause) so the result will most
replace is with comma, cause → course

2017-01-30 23:43 UTC, jtojnar commented on README.rst
> +likely a migration script of some sort.
add “be”

2017-01-30 23:44 UTC, jtojnar commented
Additionally, I feel like there are some commas missing .

2017-01-30 23:51 UTC, elbenfreund commented
Done

2017-01-30 23:52 UTC, elbenfreund commented on README.rst
> +There will be a way to import data that still constitutes valid 'facts' (that
hm, this actually looks right to me. Can you elaborate?

2017-01-31 00:01 UTC, jtojnar commented on README.rst
> +There will be a way to import data that still constitutes valid 'facts' (that
I try not to be a grammar nazi and accept that “data” can be sometimes be uncountable but IMHO when the word can be substituted for a plural word like facts or items, it should be regarded as a plural noun.

2017-01-31 03:17 UTC, jtojnar approved these changes

2017-01-31 09:02 UTC, merged