[#125] HeaderBar cleanup
projecthamster/hamster-gtk pull request #159
Opened 2017-01-31 01:13 UTC by jtojnar

2017-01-31 09:41 UTC, elbenfreund commented
I think it would be good to elaborate a bit on the use of GTK resource

2017-01-31 09:52 UTC, jtojnar commented
Updated. Now, thinking about it, compiling resources should be incorporated into the build/packaging process. Where exactly should I add it? As a dependency to some Makefile rule?

2017-01-31 09:53 UTC, elbenfreund requested changes

2017-01-31 09:53 UTC, elbenfreund commented on hamster_gtk/hamster_gtk.py
> +        """Create actions and add register them in the application."""
remove 'add'

2017-01-31 09:53 UTC, elbenfreund commented on hamster_gtk/resources/gtk/menus.ui
> +<interface>
Should we specify XML standard version and encoding?

2017-01-31 09:55 UTC, elbenfreund commented
We probably also need to make sure that resources are build as part of the release process /dist target as well as that the resulting resource file is included in the package.

2017-01-31 10:00 UTC, jtojnar commented on hamster_gtk/resources/gtk/menus.ui
> +<interface>
For XML 1.0, the header is optional.  It defaults to some Unicode encoding.

2017-01-31 10:10 UTC, jtojnar commented
I still do not understand the build process. Do I modify Makefile, MANIFEST.in or setup.py?

2017-01-31 10:18 UTC, elbenfreund commented
All of the above. :)
1. We need to declare ``build-resources`` a dependency for the dist target.
2. We need to include the resulting resource file as part of the packaging in ``setup.py``
3. We most likely need to inform our manifest.in about the new file so it doesn't issue warning.

If you prefer I could address those packaging related issues though...
Also, it may be better to not just dump the resources file in the main python code dir but use a dedicated build dir similar to what we do in ``hamster-shell-extension``.

2017-01-31 10:23 UTC, jtojnar commented
If you could tackle it, that would be great. I only see the extension creating a zipball:

https://github.com/projecthamster/hamster-shell-extension/blob/master/build.sh#L3

2017-01-31 12:38 UTC, elbenfreund commented
done. Some tests seem still trivially broken tough...

2017-02-11 16:13 UTC, elbenfreund commented on setup.py
> +        'hamster_gtk': ['resources/hamster-gtk.gresource'],
What the reason for  using a ``list`` instead of a ``tuple``?

2017-02-11 17:07 UTC, jtojnar commented on setup.py
> +        'hamster_gtk': ['resources/hamster-gtk.gresource'],
sdist is concatenating some list with the `package_data` items so with tuple it fails on the following error:

```
TypeError: can only concatenate list (not "tuple") to list
```

2017-02-14 13:55 UTC, elbenfreund approved these changes

2017-02-14 13:55 UTC, merged