[#170] Harmonize tests under misc.widgets
projecthamster/hamster-gtk pull request #181
Opened 2017-06-07 14:30 UTC by elbenfreund

Closes: #170

2017-06-07 20:50 UTC, jtojnar submitted a review, later dismissed
I am unable to test this due to #182 but it looks good to me.

2017-06-07 20:50 UTC, jtojnar commented on tests/misc/widgets/test_raw_fact_entry.py
> +from hamster_gtk.misc import widgets
Maybe this could be changed to `from hamster_gtk.misc.widgets.raw_fact_entry import RawFactEntry` to match with the other file.

2017-06-20 12:16 UTC, elbenfreund commented
rdy

2017-06-29 07:32 UTC, jtojnar requested changes

2017-06-29 07:32 UTC, jtojnar commented on tests/misc/widgets/test_raw_fact_completion.py
> +
Missing module docstring.

2017-06-29 13:35 UTC, jtojnar approved these changes

2017-06-29 14:03 UTC, merged