Refactor and Improve Overview
projecthamster/hamster-gtk pull request #185
Opened 2017-06-27 14:36 UTC by elbenfreund

This PR refactors part of the Overview related codebase (which was in big parts taken from the legacy widgets). As such we improve how totals are computed as well as move the ``get_delta_string`` method to a dedicated helper function.
On the surface level we now sow barcharts for activities and dates in the details panel as well.
Also the general look of the charts has been improved. While still do not focus too much on the aesthetics at this point this should make everything not only more appealing but also useable.

Also:
- Dates in the overview listing are not ordered (#175)

Closes: #175

2017-06-29 09:31 UTC, jtojnar requested changes

2017-06-29 09:31 UTC, jtojnar commented on hamster_gtk/overview/dialogs/overview_dialog.py
> +    # To avoid multiple calls to the backend, maybe some rudimentaty caching
rudimentaty → rudimentary

2017-06-29 09:31 UTC, jtojnar commented on hamster_gtk/helpers.py
> +    In most contexts its not that useful to present the delta in seconds.
its → it is

2017-06-29 09:31 UTC, jtojnar commented on hamster_gtk/overview/dialogs/overview_dialog.py
> +            self._charts.set_min_content_height(200)
Why these magic numbers?

2017-06-29 09:31 UTC, jtojnar commented on hamster_gtk/overview/widgets/charts.py
> +        self.override_background_color(Gtk.StateType.NORMAL, Gdk.RGBA(1, 1, 1, 1))
This is quite unreadable in dark mode:

![](https://user-images.githubusercontent.com/705123/27679769-f4527580-5cb9-11e7-9367-b97dae6b1d01.png)

2017-06-29 09:31 UTC, jtojnar commented on hamster_gtk/overview/dialogs/overview_dialog.py
> +        Result = namedtuple('Result', ('grouped_facts', 'totals'))
Why is this a named tuple when it is only ever used for simple tuple destructing.

2017-06-29 09:31 UTC, jtojnar commented on hamster_gtk/overview/widgets/charts.py
> +        grid.set_column_spacing(5)
Is it possible to use CSS for this? Maybe some selector like `#Overview grid>*`?

2017-06-29 14:10 UTC, elbenfreund commented on hamster_gtk/overview/dialogs/overview_dialog.py
> +            self._charts.set_min_content_height(200)
Otherwise the scrolled Window will not expand has the content technically can be displayed in a very small window due to scolling.

2017-06-29 14:15 UTC, jtojnar commented on hamster_gtk/overview/dialogs/overview_dialog.py
> +            self._charts.set_min_content_height(200)
I meant why it is not something like `window_width` and `window_height / 2`.

2017-06-29 14:15 UTC, elbenfreund commented on hamster_gtk/overview/dialogs/overview_dialog.py
> +        Result = namedtuple('Result', ('grouped_facts', 'totals'))
Luciano Ramalho (autor of "Fluent Python") [convincingly argues](https://talkpython.fm/episodes/show/24/fluent-python) that functions that return tuples should always return named tuples instead for readability/logging/debugging reasons. As there is no cost associated with it (other than the extra line for setting up the tuple) I came to adapt this as a best practice.

2017-06-29 23:57 UTC, elbenfreund commented on hamster_gtk/overview/widgets/charts.py
> +        grid.set_column_spacing(5)
I find the GTK+ docs really lacking in this regard, but as far as my research goes this seems not possible. [This](https://gist.github.com/ptomato/0fb634ef4098bb89026f) lists all supported properties and lacks anything related to column spacing :(

2017-06-30 04:45 UTC, elbenfreund commented
rdy

2017-06-30 17:39 UTC, jtojnar commented on hamster_gtk/overview/widgets/charts.py
> +        self.override_background_color(Gtk.StateType.NORMAL, Gdk.RGBA(1, 1, 1, 1))
That looks slightly better but still difficult to read. How do other applications deal with this?

![screenshot from 2017-06-30 19-35-42](https://user-images.githubusercontent.com/705123/27747537-ded87836-5dcb-11e7-89ce-6546678b9f2c.png)

2017-07-01 15:50 UTC, elbenfreund commented on hamster_gtk/overview/widgets/charts.py
> +        self.override_background_color(Gtk.StateType.NORMAL, Gdk.RGBA(1, 1, 1, 1))
I think GTK+ has a rather sophisticated theming support that allows for colors specific to darkmode or something similar.

2017-07-01 17:01 UTC, elbenfreund commented
I removed the changes to the colouring as they not really important right now and I would like to move on with this. theming needs to be addressed at some later stage anyway.

2017-07-01 23:31 UTC, jtojnar approved these changes

2017-07-03 14:54 UTC, merged